name: image-build
run-name: Build phpsaml-tester Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - '*'
    paths:
      - 'Dockerfile'
      - 'apache/**'
      - 'certs/**'
      - 'code/**'
      - 'php/**'
      - 'settings/**'

env:
  TAG_NAME: ${{ github.ref_type == 'tag' && format('{0}',github.ref_name) || 'latest' }}

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone
        run: sudo timedatectl set-timezone 'Europe/Athens'
      - name: Get date
        id: date
        run: echo "push_date=$(date '+%H:%M@%d/%m/%Y')" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          provenance: false
          sbom: false
          tags: gunet/phpsaml-tester:${{ env.TAG_NAME }}
          labels: gr.gunet.phpsaml-tester.pushdate=${{ steps.date.outputs.env.push_date }}
          cache-from: type=registry,ref=gunet/phpsaml-tester:buildcache
          cache-to: type=registry,ref=gunet/phpsaml-tester:buildcache,mode=max